import {
  BookOpenText,
  Bug,
  Camera,
  Codesandbox,
  Copy,
  Edit,
  FileType,
  Flame,
  Github,
  GraduationCap,
  Guitar,
  Home,
  Image,
  Link,
  Mail,
  MoonStar,
  Network,
  RefreshCcw,
  Route,
  Save,
  Search,
  Settings,
  Smile,
  Trash,
  User,
} from 'lucide-react';

// Create a type for our icon data
export type IconData = {
  icon: React.ReactNode;
  name: string;
};

export const defaultIcons: IconData[] = [
  { icon: <Camera size={24} />, name: 'Camera' },
  { icon: <Github size={24} />, name: 'Share' },
  { icon: <Route size={24} />, name: 'Copy' },
  { icon: <Smile size={24} />, name: 'Paste' },
  { icon: <RefreshCcw size={24} />, name: 'File' },
  { icon: <BookOpenText size={24} />, name: 'Add File' },
  { icon: <FileType size={24} />, name: 'Edit File' },
  { icon: <Network size={24} />, name: 'Check File' },
  { icon: <GraduationCap size={24} />, name: 'Download' },
  { icon: <Image size={24} />, name: 'Upload' },
  { icon: <Save size={24} />, name: 'Save' },
  { icon: <Trash size={24} />, name: 'Delete' },
  { icon: <Edit size={24} />, name: 'Edit' },
  { icon: <Copy size={24} />, name: 'Copy' },
  { icon: <Link size={24} />, name: 'Link' },
  { icon: <Search size={24} />, name: 'Search' },
  { icon: <Settings size={24} />, name: 'Settings' },
  { icon: <User size={24} />, name: 'User' },
  { icon: <Mail size={24} />, name: 'Mail' },
  { icon: <Home size={24} />, name: 'Home' },
  { icon: <Bug size={24} />, name: 'Bug' },
  { icon: <Codesandbox size={24} />, name: 'Codesandbox' },
  { icon: <Flame size={24} />, name: 'Flame' },
  { icon: <Guitar size={24} />, name: 'Guitar' },
  { icon: <MoonStar size={24} />, name: 'MoonStar' },
];
